CREATE TABLE manager (
    MANAGER_ID SERIAL PRIMARY KEY,
    MANAGER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES department(DEPARTMENT_ID)
);